//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringUtilisateurs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringUtilisateurs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wiki.Resources.Views.StringUtilisateurs", typeof(StringUtilisateurs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string ConnexionBoutonConnexion {
            get {
                return ResourceManager.GetString("ConnexionBoutonConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string ConnexionLienInscription {
            get {
                return ResourceManager.GetString("ConnexionLienInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string ConnexionPersistante {
            get {
                return ResourceManager.GetString("ConnexionPersistante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string ConnexionTitre {
            get {
                return ResourceManager.GetString("ConnexionTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create my account.
        /// </summary>
        public static string InscriptionBoutonInscription {
            get {
                return ResourceManager.GetString("InscriptionBoutonInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string InscriptionLienAnnuler {
            get {
                return ResourceManager.GetString("InscriptionLienAnnuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string InscriptionTitre {
            get {
                return ResourceManager.GetString("InscriptionTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ModifierMDPBoutonModifier {
            get {
                return ResourceManager.GetString("ModifierMDPBoutonModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ModifierMDPLienAnnuler {
            get {
                return ResourceManager.GetString("ModifierMDPLienAnnuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing password.
        /// </summary>
        public static string ModifierMDPTitre {
            get {
                return ResourceManager.GetString("ModifierMDPTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string ProfilBoutonSauvegarder {
            get {
                return ResourceManager.GetString("ProfilBoutonSauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProfilLienAnnuler {
            get {
                return ResourceManager.GetString("ProfilLienAnnuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my password.
        /// </summary>
        public static string ProfilLienModifierMDP {
            get {
                return ResourceManager.GetString("ProfilLienModifierMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfilTitre {
            get {
                return ResourceManager.GetString("ProfilTitre", resourceCulture);
            }
        }
    }
}
