//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Revision = 1;
        }
    
        public string Titre { get; set; }
        public string Contenu { get; set; }
        public int Revision { get; set; }
        public int IdContributeur { get; set; }
        public System.DateTime DateModification { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
